// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import 'dotenv/config';
import { defineConfig } from 'prisma/config';

// DIRECT_URL is used by the migration engine (non-pooled connection)
// Falls back to DATABASE_URL for local development
const databaseUrl = process.env['DIRECT_URL'] || process.env['DATABASE_URL'];
if (!databaseUrl) {
  throw new Error('DIRECT_URL or DATABASE_URL is required');
}

export default defineConfig({
  schema: 'prisma',
  // No `seed` command on purpose: production starts from an empty database.
  // `prisma migrate reset` leaves the schema empty; seed the admin only, on
  // demand, with `pnpm seed:admin-minimal`.
  migrations: {
    path: 'prisma/migrations',
  },
  datasource: {
    url: databaseUrl,
  },
});
